---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    Foaming: 
      $ref: "https://smart-data-models.github.io/dataModel.OCF/Foaming/model.yaml#/Foaming"
info:
  description:  |
    This Resource describes the attributes associated with foaming. The Property 'foamstrength' of the liquid is represented as an integer.The foam strength is an integer, the range of which may be enforced by the presence of the Property 'range'.
  title: Foaming
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Foaming
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/Foaming/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/Foaming/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
