---
# Copyleft (c) 2021 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    WaterInfo: 
      $ref: "https://smart-data-models.github.io/dataModel.OCF/WaterInfo/model.yaml#/WaterInfo"
info:
  description:  |
    Smart Data Models Program adaptation of the original IoTData data Models. This Resource describes the water information to indicate type of water currently provided by the device. The water type can be read or set. The Property 'supportedwatertypes' is an array of the possible water types are defined by the enumeration ['cold', 'hot', 'ambient', 'ice']. The Property 'supportedadditivetypes' is an array of the possible additive types for water. The additive types mean optional types that can be added to the specific water type according to Client's preference and are defined by the enumeration ['none', 'soda', 'mineral']. If absent, the default value is 'none'.  The Property 'currentwatertype' is the currently desired water type.  The Property 'currentadditivetypes' is the currently desired additive type(s).  For example, if 'cold' is selected with the 'currentwatertype', 'soda' and 'mineral' or both can be selected as 'currentadditivetypes'. Note that if 'hot' is selected with the 'currentwatertype', 'soda' and 'mineral' may be restricted for the 'currentadditivetypes'.
  title: WaterInfo
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - WaterInfo
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/WaterInfo/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/WaterInfo/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
