---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    movement: 
      $ref: "https://smart-data-models.github.io/dataModel.OCF/movement/model.yaml#/movement"
info:
  description:  |
    Smart Data Models Program adaptation of the original IoTData data Models. This Resource specifies linear movement. The Property 'movementSettings' is an array of strings containing possible movement values (e.g. spin, stop, left, right). The Property 'movement' is the currently selected movement value. The Property 'movementModifier' is a modifier to the movement value (e.g. 'spin', '90') 
  title: movement
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - movement
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/movement/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/movement/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
