---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    Deodorization: 
      $ref: "https://smart-data-models.github.io/dataModel.OCF/Deodorization/model.yaml#/Deodorization"
info:
  description:  |
    Smart Data Models Program adaptation of the original IoTData data Models. This Resource describes a deodorization function, which can be supported by controlling on air filter.   The Property 'mode' is a mode of the deodorization function. The supported modes are defined by the enumeration ['off', 'on', 'auto'].  'off' means that the deodorization function is not enabled. 'on' means that the deodorization function is active. 'auto' means that the deodorization function is automatically controlled depending on sensed air condition in the device inside.  The Property 'currentstate' is the current state of the deodorization function. In the case of 'auto' mode, if the sensed air condition is determined to be bad, the function will be 'on'. Then, 'mode' value is 'auto' and 'currentstate' value is 'on'. If not, the function is remaining 'off' state. Then, 'currentstate' value is 'off'.
  title: Deodorization
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Deodorization
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/Deodorization/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/Deodorization/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
