---
# Copyleft (c) 2021 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    consumable: 
      $ref: "https://smart-data-models.github.io/dataModel.OCF/consumable/model.yaml#/consumable"
info:
  description:  |
    Smart Data Models Program adaptation of the original IoTData data Models. This Resource specifies a thing that can be consumed such as filter material, printer toner etc The Propert 'typeofconsumable' is an enumeration defining the thing being consumed as defined by the Smart Home Device Specification The Property 'remaining' is an integer capturing the percentatge remaining life The Property 'orderpercentage' is an integer capturing the percentage life at which replacement or replenishment is recommended by the manufacturer The Property 'url' is a string containing a URL at which further information may be obtained with respect to the consumable.
  title: consumable
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - consumable
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/consumable/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/consumable/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
