---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    Saturation: 
      $ref: "https://smart-data-models.github.io/dataModel.OCF/Saturation/model.yaml#/Saturation"
info:
  description:  |
    Smart Data Models Program adaptation of the original IoTData data Models. This Resource describes a Colour saturation value. The Property 'colourSaturation' is an integer. A 'colourSaturation' has a range of [0,100]. A 'colourSaturation' value of 0 means producing black and white images. A 'colourSaturation' value of 50 means producing device specific normal colour images. A 'colourSaturation' value of 100 means producing device very full colour images. 
  title: Saturation
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Saturation
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/Saturation/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/Saturation/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
