---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    VehicleConnector: 
      $ref: "https://smart-data-models.github.io/dataModel.OCF/VehicleConnector/model.yaml#/VehicleConnector"
info:
  description:  |
    This Resource describes the attributes associated with an electric vehicle charging connector. The Property 'connected' is a boolean indicating the status of the connector (False = disconnected, True = connected). The Property 'ratedchargingcapacity' and 'rateddischargingcapacity' are in Amps (A).
  title: VehicleConnector
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - VehicleConnector
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/VehicleConnector/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OCF/VehicleConnector/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
